INSERT INTO `usuario`( `dni`, `vip`) VALUES ('1111',true)
INSERT INTO `usuario`( `dni`, `vip`) VALUES ('2222',false)

INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod1',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod2',200)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod3',300)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod4',400)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod5',500)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod6',600)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod7',700)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod8',800)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod9',900)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod10',1000)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod11',1100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod12',1200)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod13',1300)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod14',1400)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod15',1500)
