INSERT INTO `usuario`( `dni`, `vip`) VALUES ('1111',true)
INSERT INTO `usuario`( `dni`, `vip`) VALUES ('2222',false)

INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod1',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod2',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod3',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod4',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod5',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod6',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod7',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod8',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod9',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod10',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod11',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod12',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod13',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod14',100)
INSERT INTO `producto`(`nombre`, `valor`) VALUES ('prod15',100)
